name: CI Jest Tests
on: 
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm i
    - name: Run all tests
      run: npm t